version: 2
jobs:
  build:
    working_directory: ~/chatapp-eureka
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: chatapp-eureka-{{checksum "pom.xml"}}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: chatapp-eureka-{{checksum "pom.xml"}}
      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/chatapp-euraka-1.0.1-SNAPSHOT.jar

      - deploy:
          name: Publish to docker hub
          command: |
            docker login -e DOCKER_EMAIL -u DOCKER_USERNAME -p DOCKER_PASSWORD
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push DOCKER_USERNAME/dockerapp:$CIRCLE_SHA1
            docker push DOCKER_USERNAME/dockerapp:latest
