version: 2
jobs:
  build:
    working_directory: ~/chatapp-eureka
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: chatapp-eureka-{{checksum "pom.xml"}}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: chatapp-eureka-{{checksum "pom.xml"}}
      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/chatapp-euraka-1.0.1-SNAPSHOT.jar

      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t tommygoossens/chatapp-eureka .
            echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
            docker push tommygoossens/chatapp-eureka